#apiVersion: v1
#kind: Secret
#metadata:
#  namespace: crossplane-system
#  name: hcloud-token-secret
#type: Opaque
#data:
#  credentials: BASE64_ENCODED_HCLOUD_TOKEN
---
apiVersion: hetzner.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: hcloud-token-secret
      key: credentials
